name: Build and Deploy
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Build Go App
        run: go build -o dra_app main.go

      - name: Save the Binary as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dra_app-binary
          path: dra_app

      - name: Save an Environment Variable as output
        run: |
          DRA_ENV="This is from GA"
          echo "draenv=$DRA_ENV" >> $GITHUB_OUTPUT

      - name: Save Timestamp as State
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "build_timestamp=$TIMESTAMP" >> $GITHUB_STATE

      - name: Set Go version as an Env Value 
        run: echo "GO_VERSION=$(go version | awk '{print $3}')" >> $GITHUB_ENV


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: always()  # Ensure the job runs always, regardless of the first job's status

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dra_app-binary
      
      - name: Set Executable Permissions
        run: chmod +x dra_app
 
      - name: Deploy Go App
        run: ./dra_app
        
      - name: Retrieve the Timestamp
        run: |
          TIMESTAMP=${{needs.build.outputs.build_timestamp}}
          DRA_ENV=${{needs.build.outputs.draenv}}
          echo "Deployment completed at timestamp $TIMESTAMP and environment variable $DRA_ENV was setus"

      - name: Install jq and Add it to PATH
        run: |
          sudo apt-get update
          sudo apt-get install jq -y
          echo "/usr/bin" >> $GITHUB_PATH

      - name: Read Package Version
        uses: tyankatsu0105/read-package-version-actions@v1
