name: Setup and Build

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build Go App
        run: go build -o dra_app main.go

      - name: Save an Environment v version as output
        run: |
          DRA_ENV="This is from GA"
          echo "::set-output name=draenv::$DRA_ENV"

      - name: Save Timestamp as State
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "::save-state name=build_timestamp::$TIMESTAMP"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Go App
        run: './dra-app'
      
      - name: Retrieve the Timestamp
        run: |
          TIMESTAMP=${{needs.build.outputs.build_timestamp}}
          DRA_ENV=${{needs.build.outputs.draenv}}
          echo "Deployment completed at timestamp $TIMESTAMP and environment variable $DRA_ENV was setus"

    
    
        


      
