
name: My Workflow

on:

  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Read Package Version
        uses: tyankatsu0105/read-package-version-actions@v1
